### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by FoggyFinder** [granicz/SiteFi#10]

**Comment by granicz** [comment]
Good point, what license would be most appropriate for it? WebSharper itself is Apache 2. I would like to release SiteFi on a worry-free license, it's just code that helps people do more.

**Comment by FoggyFinder** [comment]
Dunno. Maybe MIT. It is very common.

**Comment by granicz** [comment]
Added MIT, the sample blog already stated it's under MIT.
