### ISSUE TITLE
Add support for multilingual blog

### ISSUE THREAD

**Issue by FoggyFinder** [granicz/SiteFi#12]
It would be very nice to see this feature

**Comment by granicz** [comment]
You mean multilingual (English, etc.) or with support for other programming languages in addition to F#? If the former, that would be similar to #11.

**Comment by FoggyFinder** [comment]
oh, right, I meant `multilingual`

**Comment by granicz** [comment]
How would that look like, articles in a given language grouped together? Can you link an example blog?

**Comment by FoggyFinder** [comment]
https://fornever.me/en/archive.html | https://fornever.me/ru/archive.html

**Comment by granicz** [comment]
See the above commit and updated README for instructions.
